apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicdtest-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sebokoslav/ci-cd-test-app.git
    targetRevision: HEAD
    path: config
  destination: 
    server: https://kubernetes.default.svc
    namespace: cicdtest

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdtest-deployment
  labels:
    app: cicdtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicdtest
  template:
    metadata:
      labels:
        app: cicdtest
    spec:
      containers:
      - name: cicdtest
        image: sebokoslav/ci-cd-test-app:v1.0.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cicdtest-service
spec:
  type: NodePort
  selector:
    app: cicdtest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30101
