apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicdtest-application-stage
  namespace: cicdtest-stage
spec:
  project: default

  source:
    repoURL: https://github.com/sebokoslav/ci-cd-test-app.git
    targetRevision: stage
    path: config
  destination: 
    server: https://kubernetes.default.svc
    namespace: cicdtest-stage

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdtest-deployment-stage
  labels:
    app: cicdtest-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicdtest-stage
  template:
    metadata:
      labels:
        app: cicdtest-stage
    spec:
      containers:
      - name: cicdtest-stage
        image: sebokoslav/ci-cd-test-app:v1.0.16
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cicdtest-service-stage
spec:
  type: LoadBalancer
  selector:
    app: cicdtest-stage
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 80
