name: Debug workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo ${{ GITHUB_REF#refs/*/ }}