name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        APP_NAME: ${{secrets.DOCKER_USER}}/ci-cd-test-app:$(date +%s)
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        cd src/CiCdTestApp/CiCdTestApp/
        docker build . --file ../src/Dockerfile --tag ci-cd-test-app:$(date +%s)
    - name: Docker push
      run: docker push $APP_NAME
